copy /y .\dist\gdx.jar ..\..\libgdx-vm\trunk\libraries\LibGdx\libs
copy /y .\dist\sources\gdx-sources.jar ..\..\libgdx-vm\trunk\libraries\LibGdx\libs
copy /y .\dist\gdx-backend-android.jar ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs
copy /y .\dist\sources\gdx-backend-android-sources.jar ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs
copy /y .\tests\gdx-tests-android\libs\armeabi\libgdx.so ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs\armeabi
copy /y .\tests\gdx-tests-android\libs\armeabi\libandroidgl20.so ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs\armeabi
copy /y .\tests\gdx-tests-android\libs\armeabi-v7a\libgdx.so ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs\armeabi-v7a
copy /y .\tests\gdx-tests-android\libs\armeabi-v7a\libandroidgl20.so ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs\armeabi-v7a
copy /y .\tests\gdx-tests-android\libs\x86\libgdx.so ..\..\libgdx-vm\trunk\libraries\LibGdxAndroid\libs\x86
copy /y .\dist\gdx-natives.jar ..\..\libgdx-vm\trunk\libraries\LibGdxDesktop\libs
copy /y .\dist\gdx-backend-lwjgl.jar ..\..\libgdx-vm\trunk\libraries\LibGdxDesktop\libs
copy /y .\dist\gdx-backend-lwjgl-natives.jar ..\..\libgdx-vm\trunk\libraries\LibGdxDesktop\libs
copy /y .\dist\sources\gdx-backend-lwjgl-sources.jar ..\..\libgdx-vm\trunk\libraries\LibGdxDesktop\libs
copy /y .\dist\gdx-backend-gwt.jar ..\..\libgdx-vm\trunk\libraries\LibGdxHtml\war\WEB-INF\lib
copy /y .\dist\sources\gdx-backend-gwt-sources.jar ..\..\libgdx-vm\trunk\libraries\LibGdxHtml\war\WEB-INF\lib
copy /y .\dist\extensions\gdx-tools\gdx-tools.jar ..\..\libgdx-vm\trunk\xtra\Tools\libs
copy /y .\dist\extensions\gdx-tools\sources\gdx-tools-sources.jar ..\..\libgdx-vm\trunk\xtra\Tools\libs